main = ".open-next/worker.js"
name = "irjep-web"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[env.production]
vars = { NODE_ENV = "production" }
