name = "irjep"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# ðŸ‘‡ Point to app build output
main = "apps/web/.open-next/worker.js"

[assets]
directory = "apps/web/.open-next/assets"
binding = "ASSETS"

workers_dev = true
